[package]
name = "dicom-volume"
version = "0.1.0"
authors = ["David Peherstorfer"]
edition = "2024"
description = "A high-level API for handling multiple DICOM files as volumes"
license = "Apache-2.0"
keywords = ["dicom", "volume", "3d"]

[dependencies]
